import Mutton from "../assets/Dishes/Mutton biryani.png";
import Naan from "../assets/Dishes/Naan.jpg";
import Soup from "../assets/Dishes/Soup.png";
import Tandoori from "../assets/Dishes/Tandoori.png";
import pepper from "../assets/Dishes/pepper chicken.png";
import biryani from "../assets/Dishes/categories/biryani.png";
import curries from "../assets/Dishes/categories/curries.png";
import drinks from "../assets/Dishes/categories/drinks.png";
import egg from "../assets/Dishes/categories/egg.png";
import fish from "../assets/Dishes/categories/fish.png";
import natikodi from "../assets/Dishes/categories/natikodi.png";

export const MENU = [
	{
		id: "8KJZ",
		category: "VEG STARTERS",
		items: [
			{ id: "9znpuUZ", item: "PANEER NOODLES", price: "210.00" },
			{ id: "34ZzVfi", item: "SCHEZWAN VEG NOOLES", price: "170.00" },
			{ id: "7NfPZUi", item: "GOBI MANCHURIAN", price: "140.00" },
			{ id: "3DqxA7r", item: "NOODLES NON VEG", price: "200.00" },
			{ id: "5GqaySo", item: "G0BI 65", price: "140.00" },
			{ id: "6jEPDYU", item: "CHICKEN NOODLES", price: "200.00" },
			{ id: "5t6BeCF", item: "GOBI KABAB", price: "140.00" },
			{ id: "6FvUDin", item: "MIXED VEG NOODLES", price: "300.00" },
			{ id: "9VSuBm9", item: "GOBI CHILLY", price: "140.00" },
			{ id: "9hB7pPM", item: "MUSHROOM MANCHURIYAN", price: "250.00" },
			{ id: "4ewmUHM", item: "MUSHROOM 18", price: "250.00" },
			{ id: "4yrGWc4", item: "PEPPER MUSHROOM", price: "250.00" },
			{ id: "6ouWFmF", item: "MUSHROOM KABAB", price: "250.00" },
			{ id: "58R2dMy", item: "MUSHROOM 65", price: "250.00" },
			{ id: "eva7Tyb", item: "PANEER MANCHURIYAN", price: "260.00" },
			{ id: "8rbqLRM", item: "PANEER KABAB", price: "260.00" },
			{ id: "8PtENCZ", item: "PANEER STICKS", price: "260.00" },
			{ id: "9uVB7D6", item: "PANEER MAJESTICK", price: "260.00" },
			{ id: "BWjusVt", item: "PANEER 65", price: "260.00" },
			{ id: "AH3RHTP", item: "PEPPER PANEER", price: "260.00" },
			{ id: "7tvgETR", item: "VEG LALLIPOP", price: "180.00" },
			{ id: "8Ea6mpd", item: "VEG IB", price: "180.00" },
			{ id: "Ax9FVJH", item: "BABY CORN MANCHURIYAN", price: "230.00" },
			{ id: "6NMx9uW", item: "BABY CORN CHILLY", price: "230.00" },
			{ id: "AmLuXvn", item: "VEG BULLETS", price: "180.00" },
			{ id: "ZsHqLwN", item: "VEG DIAMOND", price: "180.00" },
			{ id: "BaNP2jG", item: "CRISPY CORN", price: "160.00" },
			{ id: "46zY4MS", item: "CASHEWNUT DRY", price: "250.00" },
			{ id: "7knF4Vz", item: "ONION PAKODA", price: "150.00" },
			{ id: "47u9pwN", item: "FINGER CHIPS", price: "140.00" },
			{ id: "Bw5s27p", item: "VEG NOODLES", price: "120.00" },
			{ id: "5Fnmawp", item: "LOLLIPOP DRY", price: "250.00" },
			{ id: "CYkhMmo", item: "HAKKA NOODLES", price: "150.00" },
			{ id: "CEQkm3J", item: "MUSHROOM NOODLES", price: "230.00" },
		],
	},
	{
		id: "yJiH",
		category: "SOUPS",
		items: [
			{ id: "8vXFJZM", item: "VEG SWEET CORN SOUP", price: "80.00" },
			{ id: "77kJhq7", item: "VEG HOT SOUR SOUP", price: "60.00" },
			{ id: "4BWHYhJ", item: "TOMATO SOUP", price: "50.00" },
			{ id: "rpVd9kR", item: "DELICIOUS SPL SOUP", price: "80.00" },
			{ id: "5jnYkHb", item: "HOT SOUR CHICKEN SOUP", price: "100.00" },
			{ id: "82mBUaj", item: "DELICIOUS SPL CHICKEN SOUP", price: "130.00" },
			{ id: "4XSaMfs", item: "DELICIOUS SPL MUTTON SOUP", price: "130.00" },
		],
	},
	{
		id: "4nWj",
		category: "CHICKEN STARTERS",
		items: [
			{ id: "5XUBdys", item: "PANEER 555", price: "260.00" },
			{ id: "A42W77H", item: "BASKET CHICKEN", price: "250.00" },
			{ id: "67hajae", item: "SIZZLE CHICKEN", price: "250.00" },
			{ id: "Bktezjk", item: "CASHEWNUT CHICKEN", price: "250.00" },
			{ id: "oumtg39", item: "CHICKEN MANGOLIA", price: "250.00" },
			{ id: "CbSoy3p", item: "CHICKEN 65", price: "250.00" },
			{ id: "CB4CJgr", item: "SILON TIKKA", price: "250.00" },
			{ id: "6aokyta", item: "CHICKEN MANCHURIYAN", price: "250.00" },
			{ id: "93mBdu4", item: "PEPPER CHICKEN", price: "250.00" },
			{ id: "3ZRhGy2", item: "CHICKEN KABAB", price: "250.00" },
			{ id: "6Vf4gRv", item: "CHICKEN SPL DRY", price: "250.00" },
			{ id: "5zV7jHn", item: "CHICKEN MAHARAJ", price: "250.00" },
			{ id: "BCNCXxc", item: "CHICKEN IB", price: "250.00" },
			{ id: "9GhsEvB", item: "CHILLY CHICKEN", price: "250.00" },
			{ id: "CZ5vgJX", item: "SPICY FRIED CHICKEN", price: "250.00" },
		],
	},
	{
		id: "8Acm",
		category: "BIRYANI",
		items: [
			{ id: "BD7ZS2F", item: "VEG BIRYANI", price: "239.00" },
			{ id: "9vxnjRQ", item: "EGG BIRYANI", price: "160.00" },
			{ id: "9RZGaDv", item: "PANEER BIRYANI", price: "260.00" },
			{ id: "4us92xk", item: "MUSHROOM BIRYANI", price: "250.00" },
			{ id: "7x7gJRF", item: "CHICKEN DUM BIRYANI", price: "240.00" },
			{ id: "BnhXdiq", item: "SPL CHICKEN BIRYANI", price: "280.00" },
			{ id: "5Gjc5nL", item: "MUTTON BIRYANI", price: "300.00" },
			{ id: "5drXZic", item: "FISH BIRYANI", price: "250.00" },
			{ id: "A2KVssU", item: "PRAWNS BIRYANI", price: "300.00" },
			{ id: "8DYyc8i", item: "NATI KODI BIRYANI", price: "280.00" },
		],
	},
	{
		id: "JceE",
		category: "BIRYANI FAMILY PACK",
		items: [
			{ id: "7bZcyWn", item: "FAMILY PACK", price: "480.00" },
			{ id: "8w25CiA", item: "PANEER BIRYANI FAMILY PACK", price: "800.00" },
			{ id: "KwVGwHb", item: "BONELESS CHICKEN FAMILY PACK", price: "300.00" },
			{ id: "CHbbULh", item: "MUTTON BIRYANI FAMILY PACK", price: "1000.00" },
			{ id: "B3yc75e", item: "NATIKODI BIRYANI FAMILY PACK", price: "900.00" },
		],
	},
	{
		id: "5hj5",
		category: "SOFT DRINKS",
		items: [
			{ id: "5WUQZKE", item: "SOFT DRINKS(250ML) ", price: "25.00" },
			{ id: "4YUVotp", item: "SOFT DRINK(500ML)", price: "50.00" },
			{ id: "Cfdq62n", item: "WATER BOTTLE(1LT)", price: "25.00" },
		],
	},
	{
		id: "4hH7",
		category: "NATIKODI ITEMS",
		items: [
			{ id: "byFtmER", item: "NATIKODI ROAST", price: "280.00" },
			{ id: "5hazHyg", item: "NATIKODI FRY", price: "280.00" },
			{ id: "wRr2jJw", item: "NATIKODI CURRY", price: "280.00" },
			{ id: "AAW6NLh", item: "NATIKODI IGURU", price: "280.00" },
			{ id: "32TyV6W", item: "NATIKODI SPL CURRY", price: "280.00" },
		],
	},
	{
		id: "35qq",
		category: "TANDOORI ITEMS",
		items: [
			{ id: "BpSVVUC", item: "TANDOORI FULL", price: "450.00" },
			{ id: "8eWytaM", item: "TANDOORI HALF", price: "230.00" },
			{ id: "8UJWPVQ", item: "PANEER TIKKA", price: "280.00" },
			{ id: "8kk85KN", item: "KALMI KABAB FULL", price: "260.00" },
			{ id: "4vkaCsB", item: "KALMI KABAB HALF", price: "150.00" },
			{ id: "BYse4HD", item: "CHICKEN TANGDI KABAB FULL", price: "280.00" },
			{ id: "9bjqnS8", item: "CHICKEN TANGDI KABAB HALF", price: "150.00" },
			{ id: "B9BMyDz", item: "PRAWNS TIKKA", price: "300.00" },
		],
	},
	{
		id: "7xtu",
		category: "CHICKEN CURRIES",
		items: [
			{ id: "9vVoetK", item: "CHICKEN CURRY", price: "250.00" },
			{ id: "CADSJKS", item: "CHICKEN CURRY BONE", price: "250.00" },
			{ id: "CrzISUE", item: "CHICKEN MUGHALAI", price: "250.00" },
			{ id: "CrzYWSS", item: "CHICKEN MAHARANI", price: "250.00" },
			{ id: "7RNFupv", item: "KADAI CHICKEN", price: "250.00" },
			{ id: "9Twk7sG", item: "RAYALASEEMA CHICKEN CURRY", price: "250.00" },
			{ id: "AVb4ZXq", item: "BUTTER CHICKEN", price: "250.00" },
			{ id: "sPPVuvT", item: "CHICKEN PUNJABI", price: "250.00" },
			{ id: "Ct2WoiT", item: "SPL CHICKEN CURRY ", price: "210.00" },
			{ id: "5sdoWK5", item: "CHICKEN AFGHANI", price: "250.00" },
			{ id: "7Jzom7i", item: "CHICKEN LACHA CURRY", price: "250.00" },
		],
	},
	{
		id: "XULU",
		category: "MUTTON CURRIES",
		items: [
			{ id: "BFjEN3k", item: "MUTTON CURRY", price: "300.00" },
			{ id: "QAiNwyp", item: "MUTTON MUGHALAI", price: "300.00" },
			{ id: "9A39cLi", item: "KADAI MUTTON", price: "300.00" },
			{ id: "6rjUQy4", item: "MUTTON RAYALASEEMA", price: "300.00" },
			{ id: "7xjmPHx", item: "BUTTER MUTTON", price: "300.00" },
			{ id: "BovwByM", item: "MUTTON PUNJABI", price: "300.00" },
			{ id: "4nct8Jx", item: "SPL MUTTON CURRY", price: "330.00" },
		],
	},
	{
		id: "8ZzD",
		category: "VEG FRIED RICE",
		items: [
			{ id: "u4LAKJD", item: "VEG FRIED RICE", price: "150.00" },
			{ id: "u4A7YTp", item: "GHEEE RICE", price: "150.00" },
			{ id: "77xTmVr", item: "JEERA RICE", price: "150.00" },
			{ id: "6svg7Km", item: "GOBI RICE", price: "150.00" },
			{ id: "7cCd4oH", item: "CASHEWNUT RICE", price: "250.00" },
			{ id: "BFx8DU2", item: "CAPSICUM RICE", price: "150.00" },
			{ id: "8oXBBBo", item: "KAJU PANEER FRIED RICE", price: "250.00" },
			{ id: "CUZMaZ7", item: "PANEER FRIED RICE", price: "260.00" },
			{ id: "CpPYWNB", item: "MUSHROOM FRIED RICE", price: "250.00" },
			{ id: "8pnN2ST", item: "TOMATO RICE", price: "150.00" },
			{ id: "7V89TxJ", item: "BIRYANI RICE", price: "120.00" },
			{ id: "BDWrF2n", item: "SCHEWZWAN FRIED RICE", price: "150.00" },
			{ id: "6dWYbry", item: "KAJU PALAV", price: "230.00" },
			{ id: "5SmfVr6", item: "VEG PALAV", price: "180.00" },
		],
	},
	{
		id: "6trP",
		category: "NONVEG FRIED RICE",
		items: [
			{ id: "8Zaa45n", item: "EGG FRIED RICE", price: "150.00" },
			{ id: "922wNKB", item: "CHICKEN FRIED RICE", price: "250.00" },
			{ id: "989ZNOB", item: "MUTTON FRIED RICE", price: "320.00" },
		],
	},

	{
		id: "43oG",
		category: "ROTI ITEMS",
		items: [
			{ id: "BxgMaTz", item: "ROTI", price: "25.00" },
			{ id: "9SuEfgz", item: "BUTTER ROTI", price: "30.00" },
			{ id: "4RcfWu3", item: "PLAIN NAAN", price: "30.00" },
			{ id: "tWotgvw", item: "BUTTER NAAN", price: "35.00" },
			{ id: "6cEWtFr", item: "GARlIC NAAN", price: "45.00" },
			{ id: "7HWoeYk", item: "KULCHA", price: "30.00" },
			{ id: "85V8dma", item: "PLAIN KULCHA", price: "25.00" },
			{ id: "bxtcdDf", item: "BUTTER KULCHA", price: "35.00" },
			{ id: "BeQSeAm", item: "MASALA KULCHA", price: "45.00" },
			{ id: "AQ4h7wt", item: "CHAPATHI", price: "30.00" },
			{ id: "8Rzm76t", item: "PULKA", price: "20.00" },
			{ id: "Bf35Tsp", item: "BEET PAROTA", price: "30.00" },
			{ id: "7HQa4Tv", item: "RING PAROTA", price: "30.00" },
			{ id: "JMs3vLJ", item: "EGG PAROTA", price: "100.00" },
			{ id: "9GmUSQU", item: "CEYOLN PAROTA", price: "60.00" },
		],
	},

	{
		id: "3odt",
		category: "MUTTON STARTERS",
		items: [
			{ id: "Bv5zjrT", item: "MUTTON FRY", price: "300.00" },
			{ id: "9zsqpBn", item: "MUTTON ROAST", price: "300.00" },
			{ id: "6uiVKdW", item: "MUTTON CHILLY", price: "300.00" },
			{ id: "5wE3ueM", item: "PEPPER MUTTON", price: "300.00" },
			{ id: "3bLuZx4", item: "MUTTON MANCHURIYAN", price: "300.00" },
			{ id: "AA8CRz5", item: "MUTTON KABAB", price: "300.00" },
		],
	},
	{
		id: "3xZn",
		category: "EGG DRY",
		items: [
			{ id: "3qBCGAn", item: "EGG FRY", price: "150.00" },
			{ id: "LWzgvDF", item: "EGG MANCHURIYAN", price: "150.00" },
			{ id: "Ac3wpK3", item: "EGG 65", price: "150.00" },
			{ id: "4XyfY2g", item: "EGG BURJ", price: "150.00" },
			{ id: "5iwQRfA", item: "EGG PAKODA", price: "150.00" },
		],
	},
	{
		id: "WBSh",
		category: "FISH ITEMS",
		items: [
			{ id: "6mdWurY", item: "FISH KABAB", price: "280.00" },
			{ id: "Bj9ZEf5", item: "APOLLO FISH", price: "280.00" },
			{ id: "Bqk4sBB", item: "GARLIC FISH TIKKA", price: "300.00" },
			{ id: "865osay", item: "FISH IA", price: "300.00" },
			{ id: "B8pvcNk", item: "ANDHRA FISH CURRY", price: "250.00" },
		],
	},
	{
		id: "4F6n",
		category: "PRAWNS ITEMS",
		items: [
			{ id: "8xu5aZg", item: "PRAWNS KABAB", price: "300.00" },
			{ id: "8otnR7C", item: "PRAWNS CHILLY", price: "300.00" },
			{ id: "3FUjNK8", item: "LOOSE PRAWNS", price: "300.00" },
			{ id: "BGbe4cm", item: "PEPPER PRAWNS", price: "300.00" },
		],
	},
	{
		id: "8hq3",
		category: "VEG CURRIES",
		items: [
			{ id: "5k4hahP", item: "VEG KADAI", price: "180.00" },
			{ id: "7pCi5fV", item: "VEG CHATPAT", price: "150.00" },
			{ id: "5hNpYxF", item: "VEG HYD", price: "150.00" },
			{ id: "5ZQjPcH", item: "VEG JAYAPURI", price: "150.00" },
			{ id: "DJVDfiB", item: "VEG KOLHAPURI", price: "150.00" },
			{ id: "6CZQcbA", item: "PALAK PANEER", price: "260.00" },
			{ id: "4jkbnYf", item: "PANEER BUTTER MASALA", price: "260.00" },
			{ id: "KiyEnad", item: "KADAI PANEER", price: "260.00" },
			{ id: "3XJQqxK", item: "PALAK KURMA", price: "260.00" },
			{ id: "CkmQMnU", item: "DAL FRY", price: "140.00" },
			{ id: "7rgvWNF", item: "DAL MAHAKINI", price: "150.00" },
			{ id: "3TpAPin", item: "DAL THADKA", price: "150.00" },
			{ id: "6Frqvqe", item: "TOMATO CURRY", price: "130.00" },
			{ id: "SHyULSM", item: "MUSHROOM CURRY", price: "250.00" },
			{ id: "8aiW4xG", item: "KADAI MUSHROOM", price: "250.00" },
			{ id: "43DpvHC", item: "CASHEWNUT CURRY", price: "250.00" },
			{ id: "BtjjM62", item: "KAJU PANEER", price: "250.00" },
			{ id: "9FiMqXs", item: "MIXED VEG CURRY", price: "260.00" },
			{ id: "8hMjDKM", item: "VEG METHI CHAMAN", price: "160.00" },
			{ id: "7FpYKVn", item: "CAPSICUM CURRY", price: "180.00" },
			{ id: "JK7EG6k", item: "VEG SAGVALA", price: "140.00" },
			{ id: "9KznjEY", item: "EGG CURRY", price: "150.00" },
			{ id: "7EwvhCw", item: "EGG KEEMA CURRY", price: "150.00" },
			{ id: "5ENJHm3", item: "EGG TOMATO CURRY", price: "150.00" },
		],
	},
];

export const CATEGORIES = [
	{
		category: "Biryani",
		name: "Biryani",
		sub: ["biryani", "biryani family pack"],
		image: biryani,
	},
	{
		category: "Starters",
		name: "Starters",
		sub: ["veg starters", "chicken starters", "mutton starters"],
		image: pepper,
	},
	{
		category: "Curries",
		name: "Curries",
		sub: ["veg curries", "chicken curries", "mutton curries"],
		image: curries,
	},
	{
		category: "Soups",
		name: "Soups",
		sub: ["Soups"],
		image: Soup,
	},
	{
		category: "Egg dry",
		name: "Egg",
		sub: ["Egg dry"],
		image: egg,
	},
	{
		category: "Fried rice",
		name: "Fried rice",
		sub: ["veg fried rice", "nonveg fried rice"],
		image: Mutton,
	},
	{
		category: "Soft drinks",
		name: "Soft drinks",
		sub: ["Soft drinks"],
		image: drinks,
	},
	{
		category: "Tandoori items",
		name: "Tandoori",
		sub: ["Tandoori items"],
		image: Tandoori,
	},
	{
		category: "Natikodi items",
		name: "Natikodi",
		sub: ["Natikodi items"],
		image: natikodi,
	},
	{
		category: "Roti items",
		name: "Roti",
		sub: ["Roti items"],
		image: Naan,
	},
	{
		category: "Sea Food",
		name: "Sea Food",
		sub: ["Fish items", "Prawns items"],
		image: fish,
	},
	// {
	// 	category: "Prawns items",
	// 	name: "Prawns items",
	// 	sub: ["Prawns items"],
	// 	image: prawns,
	// },
];
